apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  labels:
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002
    protocol: TCP
    name: http
  selector:
    app: tea
